# Generated by Django 3.2 on 2021-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=0, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
